--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pierre
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: pierre
  template: 
    metadata: 
      labels: 
        app: pierre
    spec: 
      containers: 
        - 
          image: tchocothepierre/pipeline-demo
          imagePullPolicy: Always
          name: pierre
          ports: 
            ? "-containerPort"
            : 80

